import {
  readAdmins,
  readApiData,
  readBoards,
  readCities,
  readClasses,
  readCompetitions,
  readCountries,
  readExamCenters,
  readExamCentersMapping,
  readOrderConfigs,
  readPayments,
  readProductCategories,
  readProducts,
  readRelationshipManagers,
  readSMSConfigs,
  readSMTPConfigs,
  readSchools,
  readSiteConfigs,
  readStates,
  readStudents,
  readSubjects,
  readSuperAdmins,
  readTeachers,
  readTempates,
} from "@/utilities/API";
import { FormType } from "./formTypeMapper";

export const formTypeToFetcherMapper = (formType: FormType) => {
  const mapper: any = {
    Students: readStudents,
    Teachers: readTeachers,
    "Relationship Managers": readRelationshipManagers,
    "Super Admins": readSuperAdmins,
    Admins: readAdmins,
    Country: readCountries,
    State: readStates,
    City: readCities,
    Competition: readCompetitions,
    Board: readBoards,
    School: readSchools,
    Class: readClasses,
    "Exam Center": readExamCenters,
    "Exam Center Mappings": readExamCentersMapping,
    Subjects: readSubjects,
    SMTPConfigs: readSMTPConfigs,
    SMSConfigs: readSMSConfigs,
    SiteConfigs: readSiteConfigs,
    OrderConfigs: readOrderConfigs,
    Templates: readTempates,
    Products: readProducts,
    Payments: readPayments,
    ProductCategory: readProductCategories,
    groups: () => readApiData("groups"),
    cohorts: () => () => readApiData("cohorts"),
  };

  return mapper[formType];
};
