import {
  IconMap,
  IconVocabulary,
  IconSchool,
  IconTrophy,
  IconChalkboard,
  IconUser,
  IconBuilding,
  IconAffiliate,
  IconDownload,
} from "@tabler/icons-react";

const NavigationLinks = (props: any) => {
  const { consoleBaseURL } = props;

  const navigationBarLinks = [
    {
      href: "",
      linkHref: "locations",
      icon: <IconUser size="2rem" />,
      color: "gray",
      label: "Locations",
      description: "All locations of the system",
      navlinks: [
        {
          href: `${consoleBaseURL}/countries`,
          icon: <IconMap size="2rem" />,
          color: "blue",
          label: "Countries",
          description: "Countries, states and cities",
        },
        {
          href: `${consoleBaseURL}/states`,
          icon: <IconMap size="2rem" />,
          color: "blue",
          label: "States",
          description: "Countries, states and cities",
        },
        {
          href: `${consoleBaseURL}/cities`,
          icon: <IconMap size="2rem" />,
          color: "blue",
          label: "Cities",
          description: "Countries, states and cities",
        },
      ],
    },
    {
      href: "",
      linkHref: "settings",
      icon: <IconUser size="2rem" />,
      color: "gray",
      label: "Settings",
      description: "All settings of the system",
      navlinks: [
        {
          href: `${consoleBaseURL}/smtp`,
          icon: <IconMap size="2rem" />,
          color: "blue",
          label: "SMTP Config",
          description: "SMTP Config",
        },
        {
          href: `${consoleBaseURL}/smsConfig`,
          icon: <IconMap size="2rem" />,
          color: "blue",
          label: "SMS Config",
          description: "SMS Config",
        },
        {
          href: `${consoleBaseURL}/templates`,
          icon: <IconMap size="2rem" />,
          color: "blue",
          label: "Templates",
          description: "Templates",
        },
        {
          href: `${consoleBaseURL}/orderConfig`,
          icon: <IconMap size="2rem" />,
          color: "blue",
          label: "Order Config",
          description: "Order Config",
        },
        {
          href: `${consoleBaseURL}/siteConfig`,
          icon: <IconMap size="2rem" />,
          color: "blue",
          label: "Site Configs",
          description: "Site Configs",
        },
        {
          href: `${consoleBaseURL}/bulkEmail`,
          icon: <IconMap size="2rem" />,
          color: "blue",
          label: "Bulk Email",
          description: "Bulk Email",
        },
      ],
    },
    {
      href: "",
      linkHref: "others",
      icon: <IconUser size="2rem" />,
      color: "gray",
      label: "Others",
      description: "All others data of the system",
      navlinks: [
        {
          href: `${consoleBaseURL}/products`,
          icon: <IconMap size="2rem" />,
          color: "blue",
          label: "Products",
          description: "Products",
        },
        {
          href: `${consoleBaseURL}/productTypes`,
          icon: <IconMap size="2rem" />,
          color: "blue",
          label: "Product Category",
          description: "Product Category",
        },
        {
          href: `${consoleBaseURL}/payments`,
          icon: <IconMap size="2rem" />,
          color: "blue",
          label: "Payments",
          description: "Payments of the system",
        },
        {
          href: `${consoleBaseURL}/dispatch`,
          icon: <IconMap size="2rem" />,
          color: "blue",
          label: "Dispatch",
          description: "dispatch of the system",
        },
        {
          href: `${consoleBaseURL}/warehouses`,
          icon: <IconMap size="2rem" />,
          color: "blue",
          label: "Warehouses",
          description: "Warehouses of the system",
        },
        {
          href: `${consoleBaseURL}/boards`,
          icon: <IconVocabulary size="2rem" />,
          color: "pink",
          label: "Boards",
          description: "Governing education boards",
        },
        {
          href: `${consoleBaseURL}/classes`,
          icon: <IconChalkboard size="2rem" />,
          color: "green",
          label: "Classes",
          description: "Grades and levels",
        },
        {
          href: `${consoleBaseURL}/markssheet`,
          icon: <IconChalkboard size="2rem" />,
          color: "green",
          label: "Marks Sheet",
          description: "Grades and levels",
        },
        {
          href: `${consoleBaseURL}/subjects`,
          icon: <IconTrophy size="2rem" />,
          color: "violet",
          label: "Subjects",
          description: "Subjects",
        },
        {
          href: `${consoleBaseURL}/groups`,
          icon: <IconChalkboard size="2rem" />,
          color: "green",
          label: "Groups",
          description: "Grades and levels",
        },
        {
          href: `${consoleBaseURL}/cohorts`,
          icon: <IconTrophy size="2rem" />,
          color: "violet",
          label: "Cohorts",
          description: "Cohorts",
        },
      ],
    },

    {
      href: `${consoleBaseURL}/schools`,
      icon: <IconSchool size="2rem" />,
      color: "yellow",
      label: "Schools",
      description: "Institutes for learning",
    },
    {
      href: `${consoleBaseURL}/students`,
      icon: <IconAffiliate size="2rem" />,
      color: "violet",
      label: "Students",
      description: "All users of the system",
    },

    {
      href: `${consoleBaseURL}/competitions`,
      icon: <IconTrophy size="2rem" />,
      color: "violet",
      label: "Competitions",
      description: "Educational quizes and games",
    },
    // {
    //   href: `${consoleBaseURL}/annoucements`,
    //   icon: <IconTrophy size="2rem" />,
    //   color: 'violet',
    //   label: 'Annoucements',
    //   description: 'Annoucements',
    // },
    {
      href: `${consoleBaseURL}/examcenters`,
      icon: <IconBuilding size="2rem" />,
      color: "cyan",
      label: "Exam Centers",
      description: "Institutes for conducting exams",
    },
    {
      href: `${consoleBaseURL}/examcentermappings`,
      icon: <IconAffiliate size="2rem" />,
      color: "teal",
      label: "Center Mappings",
      description: "Mapping seats to centers",
    },
    {
      href: `${consoleBaseURL}/assignadmitcard`,
      icon: <IconUser size="2rem" />,
      color: "gray",
      label: "Assign Admit Card",
      description: "All users of the system",
    },

    {
      href: "",
      linkHref: "users",
      icon: <IconUser size="2rem" />,
      color: "gray",
      label: "Users",
      description: "All users of the system",
      navlinks: [
        {
          href: `${consoleBaseURL}/teachers`,
          icon: <IconUser size="2rem" />,
          color: "gray",
          label: "Teachers",
          description: "All users of the system",
        },
        {
          href: `${consoleBaseURL}/relationshipmanagers`,
          icon: <IconUser size="2rem" />,
          color: "gray",
          label: "Relationship Managers",
          description: "All users of the system",
        },
        {
          href: `${consoleBaseURL}/superadmins`,
          icon: <IconUser size="2rem" />,
          color: "gray",
          label: "Super Admins",
          description: "All users of the system",
        },
        {
          href: `${consoleBaseURL}/admins`,
          icon: <IconUser size="2rem" />,
          color: "gray",
          label: "Admins",
          description: "All users of the system",
        },
      ],
    },
    {
      linkHref: "cms",
      href: "",
      icon: <IconAffiliate size="2rem" />,
      color: "gray",
      label: "CMS",
      description: "All users of the system",
      navlinks: [
        {
          href: `${consoleBaseURL}/testimonials`,
          icon: <IconUser size="2rem" />,
          color: "gray",
          label: "Testimonials",
          description: "All users of the system",
        },
        {
          href: `${consoleBaseURL}/announcements`,
          icon: <IconUser size="2rem" />,
          color: "gray",
          label: "Announcements",
          description: "All users of the system",
        },
      ],
    },
    {
      linkHref: "download",
      href: "",
      icon: <IconDownload size="2rem" />,
      color: "gray",
      label: "Download",
      description: "All users of the system",
      navlinks: [
        {
          href: `${consoleBaseURL}/admitcard`,
          icon: <IconUser size="2rem" />,
          color: "gray",
          label: "Admit Card",
          description: "All users of the system",
        },
        {
          href: `${consoleBaseURL}/markssheetdownload`,
          icon: <IconUser size="2rem" />,
          color: "gray",
          label: "Marks Sheet",
          description: "All users of the system",
        },
        {
          href: `${consoleBaseURL}/certificate`,
          icon: <IconUser size="2rem" />,
          color: "gray",
          label: "Certificate",
          description: "All users of the system",
        },
        {
          href: `${consoleBaseURL}/omrsheet`,
          icon: <IconUser size="2rem" />,
          color: "gray",
          label: "OMR Sheet",
          description: "All users of the system",
        },
        {
          href: `${consoleBaseURL}/attendancesheet`,
          icon: <IconUser size="2rem" />,
          color: "gray",
          label: "Attendance Sheet",
          description: "All users of the system",
        },
        {
          href: `${consoleBaseURL}/medalwinner`,
          icon: <IconUser size="2rem" />,
          color: "gray",
          label: "Medal Winner",
          description: "All users of the system",
        },
      ],
    },
    {
      linkHref: "Reports",
      href: "",
      icon: <IconAffiliate size="2rem" />,
      color: "gray",
      label: "Reports",
      description: "All users of the system",
      navlinks: [
        {
          href: `${consoleBaseURL}/reports`,
          icon: <IconUser size="2rem" />,
          color: "gray",
          label: "Reports",
          description: "All users of the system",
        },
      ],
    },
  ];

  return navigationBarLinks;
};

export default NavigationLinks;
